package com.foreverrafs.superdiary.fakes

import com.foreverrafs.superdiary.ai.api.DiaryAI
import com.foreverrafs.superdiary.ai.domain.model.DiaryChatMessage
import com.foreverrafs.superdiary.domain.model.Diary
import com.foreverrafs.superdiary.domain.model.WeeklySummary
import kotlin.time.ExperimentalTime
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.onCompletion

class FakeDiaryAI : DiaryAI {
    override fun generateDiary(
        prompt: String,
        wordCount: Int,
    ): Flow<String> = flowOf("This is a sample diary generated by fake AI")

    @OptIn(ExperimentalTime::class)
    override fun generateSummary(
        diaries: List<Diary>,
        onCompletion: suspend (summary: WeeklySummary) -> Unit,
    ): Flow<String> {
        val completeSummary = "This is a sample summary generated by fake AI"

        val flow = flow {
            val words = completeSummary.split("")
            words.forEach { word ->
                delay(5000)
                emit(word)
            }
        }.onCompletion {
            onCompletion(WeeklySummary(completeSummary))
        }

        return flow
    }

    override suspend fun queryDiaries(messages: List<DiaryChatMessage>): String? =
        "This is a sample diary queried by fake AI"
}
