package com.foreverrafs.superdiary.fakes

import com.foreverrafs.superdiary.ai.api.DiaryAI
import com.foreverrafs.superdiary.domain.model.Diary
import com.foreverrafs.superdiary.domain.model.WeeklySummary
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.onCompletion

class FakeDiaryAI : DiaryAI {
    override fun generateDiary(
        prompt: String,
        wordCount: Int,
    ): Flow<String> = flowOf("This is a sample diary generated by fake AI")

    override fun generateSummary(
        diaries: List<Diary>,
        onCompletion: suspend (summary: WeeklySummary?) -> Unit,
    ): Flow<String> {
        val completeSummary = "This is a sample summary generated by fake AI"

        val flow = flow {
            val words = completeSummary.split(" ")
            val stringBuilder = StringBuilder()

            words.forEach { word ->
                delay(200)

                stringBuilder.append(word)
                stringBuilder.append(" ")

                emit(stringBuilder.toString())
            }
        }.onCompletion {
            onCompletion(WeeklySummary(completeSummary))
        }

        return flow
    }

    override suspend fun generateWritingInsights(diaries: List<Diary>): String =
        """
        Patterns — Your recent entries balance quick observations with a few longer reflections.

        Consistency — You write regularly, and your more detailed entries tend to appear later in the week.

        Try next — Add one sensory detail to your next entry to make the memory easier to revisit.
        """.trimIndent()
}
