package com.foreverrafs.superdiary.fakes

import com.foreverrafs.superdiary.ai.api.DiaryAI
import com.foreverrafs.superdiary.ai.domain.model.DiaryChatMessage
import com.foreverrafs.superdiary.domain.model.Diary
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf

class FakeDiaryAI : DiaryAI {
    override fun generateDiary(
        prompt: String,
        wordCount: Int,
    ): Flow<String> = flowOf("This is a sample diary generated by fake AI")

    override fun generateSummary(diaries: List<Diary>): Flow<String> =
        flowOf("This is a sample summary generated by fake AI")

    override suspend fun queryDiaries(messages: List<DiaryChatMessage>): String? = "This is a sample diary queried by fake AI"
}
