name: Build Release

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Lint all modules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektAll

  build:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Lint all modules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektAll

      - name: Build Android App (Release)
        id: release_build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: androidApp:assemble
          gradle-home-cache-cleanup: false
          cache-read-only: false
