name: Build Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    if: ${{ github.event_name != 'push' || github.event.pull_request.number }}
    runs-on: macos-14
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktlint on all modules
        run: ./gradlew ktlintCheck
  build:
    if: ${{ github.event_name != 'push' || github.event.pull_request.number }}
    runs-on: macos-14
    needs: lint
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Lint all modules
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ktlintCheck

      - name: Build Android App (Release)
        id: release_build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: androidApp:app:assemble
          gradle-home-cache-cleanup: false
          cache-read-only: false
