name: Lint

on:
    push:
        branches: [ main, development ]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Lint:
        env:
            SENTRY_BASE_URL_ANDROID: ${{secrets.SENTRY_BASE_URL_ANDROID}}
            SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
        runs-on: macos-14
        steps:
            -   uses: actions/checkout@v4
                with:
                    lfs: true

            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '17'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Run ktlint on all modules
                run: ./gradlew ktlintCheck

