name: Multiplatform Build

on:
    push:
        branches: [ development ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    housekeeping:
        env:
            SENTRY_BASE_URL_ANDROID: ${{secrets.SENTRY_BASE_URL_ANDROID}}
            SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
            GOOGLE_SERVER_CLIENT_ID: ${{secrets.GOOGLE_SERVER_CLIENT_ID}}
            MAPS_API_KEY_ANDROID: ${{secrets.MAPS_API_KEY_ANDROID}}
            OPENAI_KEY: ${{secrets.OPENAI_KEY}}
            STORE_FILE_BASE64: ${{secrets.SIGNING_KEY_BASE64}}
            STORE_PASSWORD: ${{secrets.SIGNING_KEYSTORE_PASSWORD}}
            KEY_ALIAS: ${{secrets.SIGNING_KEY_ALIAS}}
            KEY_PASSWORD: ${{secrets.SIGNING_KEY_PASSWORD}}
            SUPABASE_URL: ${{secrets.SUPABASE_URL}}
            SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}

        if: github.event_name != 'pull_request'
        name: Housekeeping
        runs-on: macos-14
        steps:
            -   uses: actions/checkout@v4
                with:
                    lfs: true

            -   name: Build Android App (Release)
                run: ./gradlew androidApp:app:assembleRelease

            -   name: Upload APK artifact
                if: success()
                uses: actions/upload-artifact@v4
                with:
                    name: apk-release
                    path: androidApp/app/build/outputs/apk/release/app-release.apk
