name: Snapshot Tests

on:
    workflow_run:
        workflows: [Danger]
        types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    env:
        SENTRY_BASE_URL_ANDROID: ${{secrets.SENTRY_BASE_URL_ANDROID}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktlint on all modules
        run: ./gradlew ktlintCheck
  test:
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
        BUILD_NUMBER: ${{github.event.number}}
    runs-on: macos-14
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Snapshot test (shared-ui)
        run: ./gradlew verifyPaparazziDebug

      - name: Commit and Push Images to GitHub Pages
        if: failure()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan paparazzi-snapshots-$BUILD_NUMBER
          git reset
          cp -R shared-ui/build/paparazzi/failures/delta-* .
          git add delta-*
          git commit -m "Upload paparazzi failures"
          git push --force origin paparazzi-snapshots-$BUILD_NUMBER

      - name: Generate snapshot difference markdown
        if: failure()
        run: ./gradlew createPaparazziReportComment

      - name: Comment snapshot difference markdown file on PR
        uses: thollander/actions-comment-pull-request@v3
        if: failure()
        with:
            file-path: snapshots.md
            comment-tag: execution

