name: Sonar Analysis

on:
  push:
    branches: [main, development]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.event_name != 'push' || github.event.pull_request.number }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Lint all modules
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detektAll

  quality:
    if: ${{ github.event_name != 'push' || github.event.pull_request.number }}
    needs: lint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Generate XML test reports
        id: reports
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lint koverXmlReport
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Run sonar analysis
        id: sonar
        uses: gradle/gradle-build-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: sonar
