name: Sync main with develop

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Sync master with develop branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --head development --base main -t "Sync main with develop" -b "Sync main with develop branch"
