name: Sync main with develop

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Sync master with develop branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --head development --base main -t "Sync main with develop" -b "Sync main with develop branch"

