name: Build and Test

on: [ push, pull_request ]

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Lint using ktlint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: androidApp:detekt shared:detekt data:detekt

      - name: Build and run tests
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: allTests --continue --no-configuration-cache
          gradle-home-cache-cleanup: true
          cache-read-only: false
