name: iOS Unit Tests

on:
  push:
    branches: [main, development]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktlint on all modules
        run: ./gradlew ktlintCheck
  test:
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    if: ${{ github.event_name != 'push' || github.event.pull_request.number }}
    runs-on: macos-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Unit test iOS
        id: unit_tests_ios
        uses: gradle/gradle-build-action@v3
        with:
          arguments: iosSimulatorArm64Test
          gradle-home-cache-cleanup: true
          cache-read-only: false
