name: JVM Unit & Snapshot Tests

on:
  push:
    branches: [main, development]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktlint on all modules
        run: ./gradlew ktlintCheck
  test:
    env:
        SENTRY_BASE_URL_DEBUG: ${{secrets.SENTRY_BASE_URL_DEBUG}}
        SENTRY_BASE_URL_RELEASE: ${{secrets.SENTRY_BASE_URL_RELEASE}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    runs-on: macos-14
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Unit tests JVM
        id: unit_tests_jvm
        uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'


      - name: Snapshot test (shared-ui)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: verifyPaparazziDebug
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Upload Snapshot Failure Differences
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: reports
          path: AndroidApp/app/build/paparazzi/failures/
          retention-days: 1

