name: Android Build

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint using ktlint
        run: ./gradlew ktlintCheck

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run SuperDiary Tests
        run: ./gradlew allTests

